name: Trigger auto deployment for azure-todo-demo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/azure-todo-demo-AutoDeployTrigger-2ee799b2-4611-4ca0-80c3-e8e82cbc413f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURETODODEMO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURETODODEMO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURETODODEMO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.AZURETODODEMO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZURETODODEMO_REGISTRY_PASSWORD }}
          containerAppName: azure-todo-demo
          resourceGroup: azure-spring-workshop
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


